// This file was generated by Prisma for configuration
// For Prisma v6, the schema file is the primary configuration
// The DATABASE_URL environment variable is read from .env

export default {
  schema: "prisma/schema.prisma",
};

